name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Auto-assign issues and PRs
        uses: kentaro-m/auto-assign-action@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: UitmFathi
          reviewers: ''
          number-of-assignees: 1
          number-of-reviewers: 0
